### DISCUSSION TITLE
How to write the config file for training resnet50 from my code?

### DISCUSSION THREAD

**Discussion by infish155** [ashleve/lightning-hydra-template#634] [Q&A]
I want to use this to train some models on my custom data, but I don't know how to config it. Here is my config file in configs/model/myconfig.yaml
```yaml
_target_: src.models.ffia_module.FFIAImageModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.002
  weight_decay: 0.0

net:
  _target_: src.models.components.resnet.ResNet
  include_top: True
  blocks_num: [3, 4, 6, 3]
  num_classes: 4
  block: 
    _target_: src.models.components.resnet.Bottleneck
```
I thought the net config just as the param in functions like this.
```python

def resnet50(num_classes=1000, include_top=True):
    return ResNet(Bottleneck, [3, 4, 6, 3], num_classes=num_classes, include_top=include_top)
```
but I got such errors:
```bash
hydra.errors.InstantiationException: Error in call to target 'src.models.components.resnet.Bottleneck':
TypeError("Bottleneck.__init__() missing 2 required positional arguments: 'in_channel' and 'out_channel'")
full_key: model.net.block
```
I'm new to use hydra and lightning.
Can anyone tell me how to config it?
