### ISSUE TITLE
access to neptune Run obj error

### ISSUE THREAD

**Issue by zhiyuanpeng** [ashleve/lightning-hydra-template#161]
I find Neptune Run obj has more logging method can be used, like log pandas obj, so I modify the `neptune.yaml`:

```
neptune:
#  _target_: pytorch_lightning.loggers.neptune.NeptuneLogger
  _target_: neptune.new.integrations.pytorch_lightning.NeptuneLogger
  api_key: 
  project:
```

And in your `train.py`, the logger is a list:
```
    # Init lightning loggers
    logger: List[LightningLoggerBase] = []
    if "logger" in config:
        for _, lg_conf in config.logger.items():
            if "_target_" in lg_conf:
                log.info(f"Instantiating logger <{lg_conf._target_}>")
                logger.append(hydra.utils.instantiate(lg_conf)
```

In my `LightningModule` obj, I access the `Run` obj by `self.logger.experiment['']`, but find error:
```
TypeError: list indices must be integers or slices, not str
```

Because there is only one logger obj in `logger`, I fix the error by:

```
self.logger.experiment[0]['']
```
Although I fix the error, other logging methods in the logger list my not work, how to solve this problem? Thanks.
