### ISSUE TITLE
Optuna sweep stop hparams search study after some trails

### ISSUE THREAD

**Issue by hainanxzg** [ashleve/lightning-hydra-template#166]
My Optuna sweep always stops hparams search study after some trials, can you help me?
**I run my code in 5 fold cross-validation style:**

```
def train():
  acc = []
  for fold in range(fold_num):
    # init model, logger...
    train_model()
    test_model()
    acc.append(val/acc)

  return mean(acc)
```

**And the sweep YAML file is following:**

```
defaults:
  - override /hydra/sweeper: optuna
  
 optimized_metric: "val/mean_acc"

hydra:
  sweeper:
      _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
      storage: null
      study_name: null
      n_jobs: 1
  direction: maximize
  n_trials: 500

  sampler:
        _target_: optuna.samplers.TPESampler
        seed: 2021
        consider_prior: true
        prior_weight: 1.0
        consider_magic_clip: true
        consider_endpoints: false
        n_startup_trials: 10
        n_ei_candidates: 24
        multivariate: false
        warn_independent_sampling: true

```
