### ISSUE TITLE
breaking down modules into two parts (shared and specific ones)

### ISSUE THREAD

**Issue by shim94kr** [ashleve/lightning-hydra-template#190]
Hello. First, I thank you for providing this awesome template. I learn through this template a lot!

I have a question while going through your template.

Is it possible to break down the datamodule into two parts?
- prepare_data (things to do on 1 GPU/TPU, not on every GPU/TPU in distributed mode)
// 
- setup (things to do on every accelerator in distributed mode)
- train_dataloader (the training dataloader)
- val_dataloader (the validation dataloader(s))
- test_dataloader (the test dataloader(s))

Since the data preparation is only the specific part of using a dataset, I think breaking these into two parts makes it easier to extend with other datasets.

Likewise, can the model part be separated into shared and specific ones to the dataset or model?
- Computations (init).
- Optimizers (configure_optimizers)
 //
- Train loop (training_step)
- Validation loop (validation_step)
- Test loop (test_step)

Thank you!

**Comment by ashleve** [comment]
Hi,

You can abstract away whatever you want, there are many ways to achieve sharing of specific parts. 

For example, you could use [hydra recursive instantiation feature](https://hydra.cc/docs/advanced/instantiate_objects/overview/#recursive-instantiation) to instantiate pytorch Dataset class which will be passed to Datamodule on initialization:
```yaml
datamodule:
    _target_: src.datamodules.mnist_datamodule.MNISTDataModule
    data_dir: ${data_dir}
    batch_size: 64
    num_workers: 0
    pin_memory: False
    dataset:
        _target_: src.datamodules.datasets.MyDataset
        ...
```
