### ISSUE TITLE
Question: wandb logger

### ISSUE THREAD

**Issue by johnnynunez** [ashleve/lightning-hydra-template#262]
How can I use the loss metric by epoch instead global_step directly without manual creation in wandb?
And then, how to use name + "_date" for example in wandb for each train? Because in yaml only i can put one name, true?

**Comment by ashleve** [comment]
I don't see any method in wandb docs, which would allow for setting X axis default, so I don't know if it can be achieved. 

You can add the datetime to experiment name in wandb logger config:
```yaml
wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  name: "${name}_${now:%Y-%m-%d}" # "name" is set somewhere in yaml configs
```
But if your goal is to add date to the random name generated by wandb then it's not easy to achieve, since wandb name is generated only after the run is already initialized. 

Perhaps you could write a callback that modifies the wandb run name at the start of the training.
