### ISSUE TITLE
How to dynamic choose torchvision.transforms in config?

### ISSUE THREAD

**Issue by BrandonHanx** [ashleve/lightning-hydra-template#265]
Hi, many thanks for this excellent repo!

In addition to tuning some hyperparameters, sometimes I also need to see what's the difference between data augmentations.
However, if my understanding is right, we cannot directly choose which data augmentation method to use in the config file (we have to write in the src.datamodule).
Could you please give me some hints on what's the easiest way to implement this?

Thanks in advance.

**Comment by ashleve** [comment]
Most clean would be to use config groups and recursive instantiation.

```yaml
defaults:
- augmentations: default_augmentations.yaml

_target_: src.datamodules.mnist_datamodule.MNISTDataModule
data_dir: ${data_dir}
batch_size: 64
train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 0
pin_memory: False
```

In `default_augmentations.yaml`:
```yaml
_target_: torchvision.transforms.Compose
transforms: 
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.RandomRotation
      degrees: 10
      fill: 0
```

This way initialized augmentation object gets passed to datamodule as an init parameter

**Comment by BrandonHanx** [comment]
Thank you very much for your reply.
This is a good solution for me.

**Comment by BiancaZimmer** [comment]
Thanks a lot for this!
I have a followup question: Is it possible to change the values in the `transforms `statement from another config file? I have searched the internet but haven't come to a conclusion. Maybe you can help :)
Let's take the `defaults_augmentation.yaml` from above and let's say I'd want to change the `degrees` through the `datamodule.yaml`. The follwing is not working:
```
defaults:
- augmentations: default_augmentations.yaml

_target_: src.datamodules.mnist_datamodule.MNISTDataModule
data_dir: ${data_dir}
batch_size: 64
train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 0
pin_memory: False

augmentations:
    transforms:
        degrees: 50
```
Nor is
```
...
augmentations:
    transforms:
        _target_: torchvision.transforms.RandomRotation
            degrees: 50
```
The second one doesn't throw an error but the `- _target_: torchvision.transforms.ToTensor` gets lost as well as the `fill=0`

I would be very greatful for a tip!

**Comment by ashleve** [comment]
@BiancaZimmer The reason this doesn't work is that `transforms` in `default_transforms.yaml` is a list of config sections:
```
transforms: 
    - _target_: torchvision.transforms.ToTensor
      arg1: ...
      arg2: ...
    - _target_: torchvision.transforms.RandomRotation
      arg1: ...
      arg2: ...
```

As far as I'm aware, there's no way to specify which index from the list we're trying to override, becuase there's no such syntax in hydra. The only way I know is to overrdie the whole list of transforms.

**Comment by BiancaZimmer** [comment]
@ashleve Thank you for your fast reply! I feared as much but it's good to have ones opinion verified.

**Comment by bertinma** [comment]
@ashleve Is it still impossible ? I am using hydra-zen so the only way is to use the transform index in the Compose list argument.

**Comment by bertinma** [comment]
Hi, I have a solution

I am using  hydra-zen to build my config, but I suppose it's working using "classic" hydra also because overrides work in the same way. 

This is  the example of my YAML config built 
```yaml 
datamodule:
  _target_: lightning.torch.datamodule.LightningDataModule
  train_transform:
    _target_: torchvision.transforms.v2._container.Compose
    transforms:
    - _target_: torchvision.transforms.v2._container.RandomApply
      transforms:
      - _target_: torchvision.transforms.v2._color.ColorJitter
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.2
      p: 0.3
```

I override it using this cli argument 
```bash 
datamodule.train_transform.transforms.0.p=0.2
```

So you can use it to specify `p=0`

Otherwise, I found this for hydra classic users : [https://ruhyadi.medium.com/augmentation-with-hydra-c703d474b961](url)
