### ISSUE TITLE
Change data_dir

### ISSUE THREAD

**Issue by sirtris** [ashleve/lightning-hydra-template#267]
Hi,
I'd like to do some experiments where I use different data sets. 
To do so I would just make a new `experiment.yaml` file. I have no problem overriding data modules or other defaults but when I try to override the `data_dir` it doesn't work. 

The workaround I have found for now is to remove the `data_dir` from the `train.yaml` file and put it in each experiment. 
This works fine for me but now I don't have a default setting for the `data_dir` anymore.

THX

**Comment by ashleve** [comment]
@sirtris Hi, if I understood correctly, you want to override the `data_dir` parameter from inside the experiment config? I don't experience any problems with that, take a look at this example:
```yaml
# @package _global_

defaults:
  - override /datamodule: mnist.yaml
  - override /model: mnist.yaml
  - override /callbacks: default.yaml
  - override /logger: null
  - override /trainer: default.yaml

name: "simple_dense_net"

datamodule:
  batch_size: 64

data_dir: xyz/

```

could you explain the problem a bit more more?
