### ISSUE TITLE
MLflow cannot get all experiments to show up.

### ISSUE THREAD

**Issue by 13hannes11** [ashleve/lightning-hydra-template#268]
I would like to use this template with ml flow, however, I am not sure how to properly run mlflow locally to actually get all my eperiments to show up.

i can run mlflow ui in one experiment by running the following command in the experiment foldr (e.g. `logs/experiments/runs/focusMSE_150/202203-11_13-40-16/`:

```
mlflow ui
```

but I don't know how to make all experiments show up.
Does anyone have a solution for that? Maybe that could then be added to the documentation.

I apologize if the solution is obvious but I have not gotten much experience with mlflow.

**Comment by ashleve** [comment]
@13hannes11 Unfortunately, I don't think mlflow supports recursive finding of folders containing run logs. 

The simplest solution is to set the same logging path for all runs, with a simple modification of logger config:
```yaml
mlflow:
  _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
  experiment_name: ${name}
  tracking_uri: ${original_work_dir}/logs/mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
```

I just made a PR to fix it https://github.com/ashleve/lightning-hydra-template/pull/269, feel free to review if you have any thoughts
