### ISSUE TITLE
How to set strategy=DDPStrategy() in trainer?

### ISSUE THREAD

**Issue by zhiyuanpeng** [ashleve/lightning-hydra-template#286]
As the suggestions from: [link](https://pytorch-lightning.readthedocs.io/en/stable/advanced/model_parallel.html#ddp-optimizations)
```
from pytorch_lightning.strategies import DDPStrategy

trainer = pl.Trainer(
    accelerator="gpu",
    devices=2,
    strategy=DDPStrategy(find_unused_parameters=False),
)
```
`strategy` is not a string but a function, how to set `strategy=DDPStrategy(find_unused_parameters=False)` in yaml file?
Thanks!

**Comment by ashleve** [comment]
Hydra [supports recursive instantiation](https://hydra.cc/docs/next/advanced/instantiate_objects/overview/#recursive-instantiation) so just specify strategy as a subsection in yaml with it's own `_target_`.

Example:
```yaml
trainer:
  _target_: pytorch_lightning.Trainer
  strategy:
    _target_: path.to.DDPStrategy
```
