### ISSUE TITLE
Question: How to save hydra config to wandb config.yaml

### ISSUE THREAD

**Issue by YuCao16** [ashleve/lightning-hydra-template#478]
Hello, 

I'm using `wandb` logger (and `csv` as well), I found recently `hydra` config no longer save to `wandb` 's`config.yaml` file.
Before:
```
wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: val/acc
      5: 1
      6:
      - 1
    - 1: val/acc_best
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.9.13
    start_time: 1665409636.577166
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.9.13
      5: 0.13.4
      8:
      - 5
callbacks/early_stopping/_target_:
  desc: null
  value: pytorch_lightning.callbacks.EarlyStopping
callbacks/early_stopping/check_finite:
  desc: null
  value: true
callbacks/early_stopping/check_on_train_epoch_end:
  desc: null
  value: None
callbacks/early_stopping/divergence_threshold:
  desc: null
  value: None
callbacks/early_stopping/min_delta:
  desc: null
  value: 0.0
callbacks/early_stopping/mode:
  desc: null
  value: max
callbacks/early_stopping/monitor:
  desc: null
  value: val/acc
callbacks/early_stopping/patience:
  desc: null
  value: 100
callbacks/early_stopping/stopping_threshold:
  desc: null
  value: None
callbacks/early_stopping/strict:
  desc: null
  value: true
callbacks/early_stopping/verbose:
  desc: null
  value: false
callbacks/model_checkpoint/_target_:
  desc: null
  value: pytorch_lightning.callbacks.ModelCheckpoint
callbacks/model_checkpoint/auto_insert_metric_name:
  desc: null
  value: false
callbacks/model_checkpoint/dirpath:
  desc: null
  value: /Users/caoyu/Github/lightning-hydra-template/logs/train/runs/2022-10-10_14-47-15/checkpoints
callbacks/model_checkpoint/every_n_epochs:
  desc: null
  value: None
callbacks/model_checkpoint/every_n_train_steps:
  desc: null
  value: None
callbacks/model_checkpoint/filename:
  desc: null
  value: epoch_{epoch:03d}
callbacks/model_checkpoint/mode:
  desc: null
  value: max
callbacks/model_checkpoint/monitor:
  desc: null
  value: val/acc
callbacks/model_checkpoint/save_last:
  desc: null
  value: true
callbacks/model_checkpoint/save_on_train_epoch_end:
  desc: null
  value: None
callbacks/model_checkpoint/save_top_k:
  desc: null
  value: 1
callbacks/model_checkpoint/save_weights_only:
  desc: null
  value: false
callbacks/model_checkpoint/train_time_interval:
  desc: null
  value: None
callbacks/model_checkpoint/verbose:
  desc: null
  value: false
callbacks/model_summary/_target_:
  desc: null
  value: pytorch_lightning.callbacks.RichModelSummary
callbacks/model_summary/max_depth:
  desc: null
  value: -1
callbacks/rich_progress_bar/_target_:
  desc: null
  value: pytorch_lightning.callbacks.RichProgressBar
ckpt_path:
  desc: null
  value: None
datamodule/_target_:
  desc: null
  value: src.datamodules.mnist_datamodule.MNISTDataModule
datamodule/batch_size:
  desc: null
  value: 128
datamodule/data_dir:
  desc: null
  value: /Users/caoyu/Github/lightning-hydra-template/data/
datamodule/num_workers:
  desc: null
  value: 0
datamodule/pin_memory:
  desc: null
  value: false
datamodule/train_val_test_split:
  desc: null
  value:
  - 55000
  - 5000
  - 10000
extras/enforce_tags:
  desc: null
  value: true
extras/ignore_warnings:
  desc: null
  value: false
extras/print_config:
  desc: null
  value: true
model/_target_:
  desc: null
  value: src.models.mnist_module.MNISTLitModule
model/net/_target_:
  desc: null
  value: src.models.components.simple_dense_net.SimpleDenseNet
model/net/input_size:
  desc: null
  value: 784
model/net/lin1_size:
  desc: null
  value: 64
model/net/lin2_size:
  desc: null
  value: 128
model/net/lin3_size:
  desc: null
  value: 64
model/net/output_size:
  desc: null
  value: 10
model/optimizer/_partial_:
  desc: null
  value: true
model/optimizer/_target_:
  desc: null
  value: torch.optim.Adam
model/optimizer/lr:
  desc: null
  value: 0.001
model/optimizer/weight_decay:
  desc: null
  value: 0.0
model/params/non_trainable:
  desc: null
  value: 0
model/params/total:
  desc: null
  value: 67978
model/params/trainable:
  desc: null
  value: 67978
model/scheduler/_partial_:
  desc: null
  value: true
model/scheduler/_target_:
  desc: null
  value: torch.optim.lr_scheduler.ReduceLROnPlateau
model/scheduler/factor:
  desc: null
  value: 0.1
model/scheduler/mode:
  desc: null
  value: min
model/scheduler/patience:
  desc: null
  value: 10
seed:
  desc: null
  value: 123
tags:
  desc: null
  value:
  - dev
task_name:
  desc: null
  value: train
trainer/_target_:
  desc: null
  value: pytorch_lightning.Trainer
trainer/accelerator:
  desc: null
  value: cpu
trainer/check_val_every_n_epoch:
  desc: null
  value: 1
trainer/default_root_dir:
  desc: null
  value: /Users/caoyu/Github/lightning-hydra-template/logs/train/runs/2022-10-10_14-47-15
trainer/deterministic:
  desc: null
  value: false
trainer/devices:
  desc: null
  value: 1
trainer/max_epochs:
  desc: null
  value: 3
trainer/min_epochs:
  desc: null
  value: 1
```
Now:
```
wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: val/acc
      5: 1
      6:
      - 1
    - 1: val/acc_best
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/acc
      5: 1
      6:
      - 1
    - 1: test/loss
      5: 1
      6:
      - 1
    - 1: test/acc
      5: 1
      6:
      - 1
    python_version: 3.8.15
    start_time: 1670583155.275978
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      3:
      - 2
      - 7
      - 23
      4: 3.8.15
      5: 0.13.6
      8:
      - 5
```
This may related to:
https://github.com/ashleve/lightning-hydra-template/blob/16fb9a6a807d278d1797ce4dedc885c7e5e1b7fb/src/utils/utils.py#L172
Any idea how to restore to previous state?
