### ISSUE TITLE
Question about hydra syntax

### ISSUE THREAD

**Issue by yipliu** [ashleve/lightning-hydra-template#489]
Hi, 

I would like to ask a question about the hydra syntax

>configs/model/mnist.yaml

```YAML
net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: ${modle.net.input_size} * 2
```

I want `lin1_size` to be twice the size of `input_size` all the time.

I know the above code `syntax is wrong,` is there any way to reflect it directly in the yaml file?

**Comment by ashleve** [comment]
I think it's not yet possible by default but you could define your own resolvers.
https://omegaconf.readthedocs.io/en/2.3_branch/custom_resolvers.html#custom-resolvers

**Comment by TezRomacH** [comment]
@yipliu I wrote something like that for my project :) 

```python
@rank_zero_only
def register_resolvers() -> None:
    OmegaConf.register_new_resolver("add", lambda *numbers: sum(numbers), replace=True)
    OmegaConf.register_new_resolver("mult", lambda *numbers: np.prod(numbers), replace=True)
    OmegaConf.register_new_resolver("divide", lambda x, y: x / y, replace=True)
```

then in the script register these new functions
```python
if __name__ == "__main__":
    register_resolvers()
```

your example will look like this
```yaml
net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: ${mult:${modle.net.input_size},2}
```
