### ISSUE TITLE
define multiple checkpoints

### ISSUE THREAD

**Issue by abhijeetdhakane** [ashleve/lightning-hydra-template#510]
I was a trying to define multiple checkpoints at `config/callbacks/default.yaml`, go an error:

```
model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_min_{epoch:03d}"
  monitor: "val/acc"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_min_{epoch:03d}"
  monitor: "val/acc"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

```

**Comment by ArtemisDicoTiar** [comment]
use different name for the callback.
Your error definitely happened due to duplicate name.
change like
~~~
model_checkpoint_max_acc:
...

model_checkpoint_min_acc:
...
~~~

and use the two name for calling callbacks

**Comment by abhijeetdhakane** [comment]
Thanks!!

**Comment by ArtemisDicoTiar** [comment]
yes. at this point `model_checkpoint.yaml` is the thing that you need to configure without duplicate name.
and as you override the `model_checkpoint` below the `defaults`, if the name of the checkpoint object has been changed the one you override also has to be changed.
~~~
defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
^^^^^^^^^^^^^^^^^
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/acc"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/acc"
  patience: 100
  mode: "max"

model_summary:
  max_depth: -1

~~~

**Comment by ashleve** [comment]
You can create multiple instances of model checkpoint by duplicating the `model_checkpoint.yaml`, attaching them to defaults, and setting them different names in yaml config.
```yaml
defaults:
  - model_checkpoint_1.yaml
  - model_checkpoint_2.yaml

model_checkpoint_1:
    monitor: "val/acc"
    mode: "max"

model_checkpoint_2:
    monitor: "val/loss"
    mode: "min"
```

In `model_checkpoint_1.yaml`:
```yaml
model_checkpoint_1: # each model_checkpoint_x.yaml needs to have a different section name
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: null # directory to save the model file
...
```

**Comment by abhijeetdhakane** [comment]
I tried above, but could not save checkpoint at the end of every single training epoch, while other checkpoints I'm able to save.
```
defaults:
  - model_checkpoint_1.yaml
  - model_checkpoint_2.yaml

model_checkpoint_1:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "epoch"
  every_n_epochs: 1
  save_on_train_epoch_end: True
  save_last: True

model_checkpoint_2:
    monitor: "val/loss"
    mode: "min"
```
