### ISSUE TITLE
Couldn't log with wandb

### ISSUE THREAD

**Issue by amirshamaei** [ashleve/lightning-hydra-template#607]
I successfully adopted the template. It runs smoothly. However, I cannot log in using WandB. I am new to WandB, but I set it up for my other project successfully (with lightning). The setting of yaml file is as follows:

```
wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
#  name: "mri_recon" # name of the run (normally generated by wandb)
  save_dir: "${paths.output_dir}"
  offline: False
  id: null # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: "mri_recon"
  log_model: False # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  # entity: "" # set to name of your wandb team
  group: ""
  tags: []
  job_type: ""

```

Do I need to put API key somewhere? what is the proper routine for this?
