### ISSUE TITLE
RuntimeError when using profiler.

### ISSUE THREAD

**Issue by beatwad** [ashleve/lightning-hydra-template#636]
When using "pytorch" profiler an error occurs: 
```
RuntimeError: Tried to serialize object __torch__.torch.classes.profiler._RecordFunction which does not have a __getstate__ method defined!
```

I suppose it's happening when PL Trainer module tries to save checkpoint after profiler finishes the job. Trainer by default always tries to save checkpoints even when all callbacks are disabled.

Solution: change file [configs/debug/profiler.yaml](https://github.com/ashleve/lightning-hydra-template/blob/main/configs/debug/profiler.yaml):
``` 
trainer:
  profiler: "simple"  
  # profiler: "advanced"
  # profiler: "pytorch"
  profiler: "pytorch"
  enable_checkpointing: False
```
